/**
 * Catalogo dos 54 passos do roteiro Setis PayGo v20241216.
 * Fonte: Roteiro de testes para automacoes comerciais v20241216.
 * Integracao alvo nesta tela: Biblioteca Windows / PayGo integrado.
 */
import type { TefPaymentRequest } from "@/lib/tef";

export type StepKind =
  | "manual"
  | "sale"
  | "sale-cancel"
  | "network-cancel"
  | "cancel-prev"
  | "admin"
  | "power-cut"
  | "generic-input"
  | "pending"
  | "controlpay-na";

export interface HomologationStep {
  number: number;
  name: string;
  description: string;
  procedure: string;
  verify: string;
  mandatory: boolean;
  kind: StepKind;
  sale?: Partial<TefPaymentRequest> & { acquirer?: string };
  cancelsStep?: number;
  adminCode?: number;
  expected: string;
}

export const HOMOLOGATION_STEPS: HomologationStep[] = [
  {
    number: 1,
    name: "Instalação",
    mandatory: true,
    kind: "manual",
    description: "Realize uma instalação com os dados enviados pela PayGo.",
    procedure: "Realize uma instalação com os dados enviados pela PayGo.",
    expected: "Instalação realizada com sucesso, recibo impresso. Se a instalação do PdC ou client já foi realizada, não é necessário realizar novamente.",
    verify: "Verificar mensagem ao operador, recibo quando aplicavel e confirmacao/desfazimento correto para a automacao comercial.",
  },
  {
    number: 2,
    name: "Venda com valor máximo permitido pela automação",
    mandatory: true,
    kind: "sale",
    description: "Realizar uma venda com o valor máximo permitido pela automação. Ex. R$100.000,00.",
    procedure: "Realizar uma venda com o valor máximo permitido pela automação. Ex. R$100.000,00.",
    expected: "Venda aprovada e confirmada, recibo impresso.",
    verify: "Verificar mensagem ao operador, recibo quando aplicavel e confirmacao/desfazimento correto para a automacao comercial.",
    sale: {
      amount: 100000,
      method: "credit",
      acquirer: "DEMO",
    },
  },
  {
    number: 3,
    name: "Venda à vista aprovada com pré-seleção de parâmetros",
    mandatory: true,
    kind: "sale",
    description: "Realizar uma venda de qualquer valor, pré-selecionado: ● Autorizador: DEMO; ● Forma de pagamento: Cartão; ● Tipo de cartão: Crédito; ● Tipo de financiamento: A Vista.",
    procedure: "Realizar uma venda de qualquer valor, pré-selecionado: ● Autorizador: DEMO; ● Forma de pagamento: Cartão; ● Tipo de cartão: Crédito; ● Tipo de financiamento: A Vista.",
    expected: "Venda aprovada e confirmada, recibo impresso.",
    verify: "Verificar mensagem ao operador, recibo quando aplicavel e confirmacao/desfazimento correto para a automacao comercial.",
    sale: {
      amount: 10,
      method: "credit",
      acquirer: "DEMO",
    },
  },
  {
    number: 4,
    name: "Teste para retorno de Venda Negada",
    mandatory: true,
    kind: "sale",
    description: "Realizar uma venda no valor de R$1000,01 no autorizador DEMO.",
    procedure: "Realizar uma venda no valor de R$1000,01 no autorizador DEMO.",
    expected: "Venda negada.",
    verify: "Verificar que a transacao nao seja considerada realizada pela automacao e que a mensagem/pendencia seja tratada conforme esperado.",
    sale: {
      amount: 1000.01,
      method: "credit",
      acquirer: "DEMO",
    },
  },
  {
    number: 5,
    name: "Venda negada, rede desconhecida",
    mandatory: true,
    kind: "network-cancel",
    description: "Realizar uma venda e no menu de seleção da rede, pressionar a tecla ‘Esc’ em uma solução Windows ou ‘Cancelar’ em uma solução Android.",
    procedure: "Realizar uma venda e no menu de seleção da rede, pressionar a tecla ‘Esc’ em uma solução Windows ou ‘Cancelar’ em uma solução Android.",
    expected: "Venda negada, rede não informada.",
    verify: "Verificar que a transacao nao seja considerada realizada pela automacao e que a mensagem/pendencia seja tratada conforme esperado.",
    sale: {
      amount: 5,
      method: "credit",
    },
  },
  {
    number: 6,
    name: "Venda aprovada, teste de tipo de cartão crédito",
    mandatory: true,
    kind: "sale",
    description: "Realizar uma venda de qualquer valor na modalidade crédito. Quando solicitado, inserir o cartão no PIN- Pad.",
    procedure: "Realizar uma venda de qualquer valor na modalidade crédito. Quando solicitado, inserir o cartão no PIN- Pad.",
    expected: "Venda aprovada e confirmada, recibo impresso, com cartão de crédito.",
    verify: "Verificar mensagem ao operador, recibo quando aplicavel e confirmacao/desfazimento correto para a automacao comercial.",
    sale: {
      amount: 5,
      method: "credit",
      acquirer: "DEMO",
    },
  },
  {
    number: 7,
    name: "Venda aprovada, teste de tipo de cartão débito",
    mandatory: true,
    kind: "sale",
    description: "Realizar uma venda de qualquer valor na modalidade débito. Quando solicitado, inserir o cartão no PIN-Pad.",
    procedure: "Realizar uma venda de qualquer valor na modalidade débito. Quando solicitado, inserir o cartão no PIN-Pad.",
    expected: "Venda aprovada e confirmada, recibo impresso, com cartão de débito.",
    verify: "Verificar mensagem ao operador, recibo quando aplicavel e confirmacao/desfazimento correto para a automacao comercial.",
    sale: {
      amount: 5,
      method: "debit",
      acquirer: "DEMO",
    },
  },
  {
    number: 8,
    name: "Venda aprovada, teste de tipo de financiamento",
    mandatory: true,
    kind: "sale",
    description: "Realizar uma venda de crédito parcelada pelo estabelecimento em 99 parcelas.",
    procedure: "Realizar uma venda de crédito parcelada pelo estabelecimento em 99 parcelas.",
    expected: "Venda aprovada e confirmada, recibo impresso, modalidade ‘parcelada pela loja’, em 99 parcelas.",
    verify: "Verificar mensagem ao operador, recibo quando aplicavel e confirmacao/desfazimento correto para a automacao comercial.",
    sale: {
      amount: 99,
      method: "credit",
      installments: 99,
      acquirer: "DEMO",
    },
  },
  {
    number: 9,
    name: "Venda, teste de recibos diferenciados #1 (opcional)",
    mandatory: false,
    kind: "sale",
    description: "Realizar uma venda de qualquer valor utilizando DEMO.",
    procedure: "Realizar uma venda de qualquer valor utilizando DEMO.",
    expected: "Venda aprovada e confirmada, vias impressas: ● Reduzido para o portador do cartão; ● Diferenciado para o lojista.",
    verify: "Verificar mensagem ao operador, recibo quando aplicavel e confirmacao/desfazimento correto para a automacao comercial.",
    sale: {
      amount: 3,
      method: "credit",
      acquirer: "DEMO",
    },
  },
  {
    number: 10,
    name: "Venda, teste de recibos diferenciados #2",
    mandatory: true,
    kind: "sale",
    description: "Realizar uma venda de qualquer valor utilizando DEMO.",
    procedure: "Realizar uma venda de qualquer valor utilizando DEMO.",
    expected: "Venda aprovada e confirmada, vias impressas: ● Diferenciado para o portador do cartão; ● Diferenciado para o lojista.",
    verify: "Verificar mensagem ao operador, recibo quando aplicavel e confirmacao/desfazimento correto para a automacao comercial.",
    sale: {
      amount: 4,
      method: "credit",
      acquirer: "DEMO",
    },
  },
  {
    number: 11,
    name: "Venda por QRCode para PIX e Carteiras Digitais",
    mandatory: true,
    kind: "sale",
    description: "Realizar uma venda de qualquer valor, pré-selecionado: ● Rede “PIX C6 BANK”; ● Aguardando aprovação automática.",
    procedure: "Realizar uma venda de qualquer valor, pré-selecionado: ● Rede “PIX C6 BANK”; ● Aguardando aprovação automática.",
    expected: "Venda aprovada e confirmada, recibo impresso.",
    verify: "Verificar mensagem ao operador, recibo quando aplicavel e confirmacao/desfazimento correto para a automacao comercial.",
    sale: {
      amount: 1,
      method: "pix",
      acquirer: "PIX C6 BANK",
    },
  },
  {
    number: 12,
    name: "Teste de comunicação bem-sucedido",
    mandatory: true,
    kind: "admin",
    description: "Realizar um teste de comunicação no menu administrativo.",
    procedure: "Realizar um teste de comunicação no menu administrativo.",
    expected: "Teste de comunicação bem-sucedido, mas sem recibo.",
    verify: "Verificar mensagem ao operador, recibo quando aplicavel e confirmacao/desfazimento correto para a automacao comercial.",
    adminCode: 0,
  },
  {
    number: 13,
    name: "Relatório sintético (Opcional)",
    mandatory: false,
    kind: "admin",
    description: "Realizar a emissão de um relatório sintético no menu administrativo.",
    procedure: "Realizar a emissão de um relatório sintético no menu administrativo.",
    expected: "Emissão de relatório bem-sucedido.",
    verify: "Verificar mensagem ao operador, recibo quando aplicavel e confirmacao/desfazimento correto para a automacao comercial.",
    adminCode: 17,
  },
  {
    number: 14,
    name: "Relatório detalhado (Opcional)",
    mandatory: false,
    kind: "admin",
    description: "Realizar a emissão de um relatório detalhado no menu administrativo.",
    procedure: "Realizar a emissão de um relatório detalhado no menu administrativo.",
    expected: "Emissão de relatório bem-sucedido.",
    verify: "Verificar mensagem ao operador, recibo quando aplicavel e confirmacao/desfazimento correto para a automacao comercial.",
    adminCode: 18,
  },
  {
    number: 15,
    name: "Relatório resumido (Opcional)",
    mandatory: false,
    kind: "admin",
    description: "Realizar a emissão de um relatório resumido no menu administrativo.",
    procedure: "Realizar a emissão de um relatório resumido no menu administrativo.",
    expected: "Emissão de relatório bem-sucedido.",
    verify: "Verificar mensagem ao operador, recibo quando aplicavel e confirmacao/desfazimento correto para a automacao comercial.",
    adminCode: 21,
  },
  {
    number: 16,
    name: "Operação cancelada no menu administrativo",
    mandatory: true,
    kind: "manual",
    description: "Acessar o menu de seleção na função administrativa, pressionar a tecla ‘Esc’ em uma solução Windows ou ‘Cancelar’ em uma solução Android.",
    procedure: "Acessar o menu de seleção na função administrativa, pressionar a tecla ‘Esc’ em uma solução Windows ou ‘Cancelar’ em uma solução Android.",
    expected: "Operação mal sucedida, rede não informada.",
    verify: "Verificar que a transacao nao seja considerada realizada pela automacao e que a mensagem/pendencia seja tratada conforme esperado.",
  },
  {
    number: 17,
    name: "Venda bem-sucedida #1 (Opcional)",
    mandatory: false,
    kind: "sale-cancel",
    description: "Realizar uma venda de R$ 1,00, utilizar DEMO.",
    procedure: "Realizar uma venda de R$ 1,00, utilizar DEMO.",
    expected: "Venda aprovada e confirmada, recibo impresso.",
    verify: "Verificar mensagem ao operador, recibo quando aplicavel e confirmacao/desfazimento correto para a automacao comercial.",
    sale: {
      amount: 1,
      method: "credit",
      acquirer: "DEMO",
    },
  },
  {
    number: 18,
    name: "Venda bem-sucedida #2 (Opcional)",
    mandatory: false,
    kind: "sale-cancel",
    description: "Realizar uma venda de R$ 2,00, utilizar DEMO.",
    procedure: "Realizar uma venda de R$ 2,00, utilizar DEMO.",
    expected: "Venda aprovada e confirmada, recibo impresso.",
    verify: "Verificar mensagem ao operador, recibo quando aplicavel e confirmacao/desfazimento correto para a automacao comercial.",
    sale: {
      amount: 2,
      method: "credit",
      acquirer: "DEMO",
    },
  },
  {
    number: 19,
    name: "Venda bem-sucedida #3",
    mandatory: true,
    kind: "sale-cancel",
    description: "Realizar uma venda de R$ 12.345,67, utilizar DEMO.",
    procedure: "Realizar uma venda de R$ 12.345,67, utilizar DEMO.",
    expected: "Venda aprovada e confirmada, recibo impresso.",
    verify: "Verificar mensagem ao operador, recibo quando aplicavel e confirmacao/desfazimento correto para a automacao comercial.",
    sale: {
      amount: 12345.67,
      method: "credit",
      acquirer: "DEMO",
    },
  },
  {
    number: 20,
    name: "Cancelamento bem-sucedido #1 (Opcional)",
    mandatory: false,
    kind: "cancel-prev",
    description: "Realizar o cancelamento da venda realizada no PASSO 18.",
    procedure: "Realizar o cancelamento da venda realizada no PASSO 18.",
    expected: "Operação de cancelamento bem-sucedida, recibo impresso.",
    verify: "Verificar mensagem ao operador, recibo quando aplicavel e confirmacao/desfazimento correto para a automacao comercial.",
    cancelsStep: 18,
  },
  {
    number: 21,
    name: "Cancelamento bem-sucedido #2",
    mandatory: true,
    kind: "cancel-prev",
    description: "Realizar o cancelamento da venda realizada no PASSO 19.",
    procedure: "Realizar o cancelamento da venda realizada no PASSO 19.",
    expected: "Operação de cancelamento bem-sucedida, recibo impresso.",
    verify: "Verificar mensagem ao operador, recibo quando aplicavel e confirmacao/desfazimento correto para a automacao comercial.",
    cancelsStep: 19,
  },
  {
    number: 22,
    name: "Cancelamento bem-sucedido #3 (Opcional)",
    mandatory: false,
    kind: "cancel-prev",
    description: "Realizar o cancelamento da venda realizada no PASSO 17.",
    procedure: "Realizar o cancelamento da venda realizada no PASSO 17.",
    expected: "Operação de cancelamento bem-sucedida, recibo impresso.",
    verify: "Verificar mensagem ao operador, recibo quando aplicavel e confirmacao/desfazimento correto para a automacao comercial.",
    cancelsStep: 17,
  },
  {
    number: 23,
    name: "Cancelamento bem sucedido #4 (Opcional)",
    mandatory: false,
    kind: "cancel-prev",
    description: "Realizar o cancelamento da transação realizada no PASSO 02 através do menu administrativo.",
    procedure: "Realizar o cancelamento da transação realizada no PASSO 02 através do menu administrativo.",
    expected: "Operação de cancelamento bem-sucedida, recibo impresso.",
    verify: "Verificar mensagem ao operador, recibo quando aplicavel e confirmacao/desfazimento correto para a automacao comercial.",
    cancelsStep: 2,
  },
  {
    number: 24,
    name: "Queda de energia durante uma venda",
    mandatory: true,
    kind: "power-cut",
    description: "Realizar uma venda. Desligar o checkout de maneira abrupta quando solicitada a inserção do cartão.",
    procedure: "Realizar uma venda. Desligar o checkout de maneira abrupta quando solicitada a inserção do cartão.",
    expected: "Venda não finalizada.",
    verify: "Verificar que a transacao nao seja considerada realizada pela automacao e que a mensagem/pendencia seja tratada conforme esperado.",
  },
  {
    number: 25,
    name: "Queda de energia durante uma operação administrativa",
    mandatory: true,
    kind: "power-cut",
    description: "Realizar o cancelamento da venda realizada no PASSO 06. Desligar o checkout de maneira abrupta quando solicitada a inserção do cartão.",
    procedure: "Realizar o cancelamento da venda realizada no PASSO 06. Desligar o checkout de maneira abrupta quando solicitada a inserção do cartão.",
    expected: "Venda não finalizada.",
    verify: "Verificar que a transacao nao seja considerada realizada pela automacao e que a mensagem/pendencia seja tratada conforme esperado.",
  },
  {
    number: 26,
    name: "Solicitação de dado genérico digitado 1#",
    mandatory: true,
    kind: "generic-input",
    description: "Realizar uma venda no valor R$1001,00 no autorizador DEMO.",
    procedure: "Realizar uma venda no valor R$1001,00 no autorizador DEMO.",
    expected: "Será solicitada a captura de um dado digitado na tag 0x2F.",
    verify: "Verificar captura generica da tag 0x2F e que a automacao nao envie essa tag antes de ser solicitada.",
    sale: {
      amount: 1001,
      method: "credit",
      acquirer: "DEMO",
    },
  },
  {
    number: 27,
    name: "Solicitação de dado genérico digitado 2#",
    mandatory: true,
    kind: "generic-input",
    description: "Digitar o seguinte valor para o dado digitado: ABC123.",
    procedure: "Digitar o seguinte valor para o dado digitado: ABC123.",
    expected: "Venda aprovada e confirmada, recibo impresso.",
    verify: "Verificar mensagem ao operador, recibo quando aplicavel e confirmacao/desfazimento correto para a automacao comercial.",
  },
  {
    number: 28,
    name: "Solicitação de menu genérico 1#",
    mandatory: true,
    kind: "generic-input",
    description: "Realizar uma venda no valor R$1002,00 no autorizador DEMO.",
    procedure: "Realizar uma venda no valor R$1002,00 no autorizador DEMO.",
    expected: "Será solicitada a captura de um menu que preenche a tag 0x2F.",
    verify: "Verificar captura generica da tag 0x2F e que a automacao nao envie essa tag antes de ser solicitada.",
    sale: {
      amount: 1002,
      method: "credit",
      acquirer: "DEMO",
    },
  },
  {
    number: 29,
    name: "Solicitação de menu genérico 2#",
    mandatory: true,
    kind: "generic-input",
    description: "Selecionar o item “ABCDEF”.",
    procedure: "Selecionar o item “ABCDEF”.",
    expected: "Será solicitada a captura de um menu que preenche a tag 0x2F.",
    verify: "Verificar mensagem ao operador, recibo quando aplicavel e confirmacao/desfazimento correto para a automacao comercial.",
  },
  {
    number: 30,
    name: "Venda com mensagem resultado no tamanho máximo",
    mandatory: true,
    kind: "sale",
    description: "Realizar uma venda de R$1003,00 no autorizador DEMO.",
    procedure: "Realizar uma venda de R$1003,00 no autorizador DEMO.",
    expected: "Venda aprovada com a mensagem de tamanho máximo (80 caracteres).",
    verify: "Verificar mensagem ao operador, recibo quando aplicavel e confirmacao/desfazimento correto para a automacao comercial.",
    sale: {
      amount: 1003,
      method: "credit",
      acquirer: "DEMO",
    },
  },
  {
    number: 31,
    name: "Transação pendente #1",
    mandatory: true,
    kind: "pending",
    description: "Realizar uma venda de R$1005,50 no autorizador DEMO.",
    procedure: "Realizar uma venda de R$1005,50 no autorizador DEMO.",
    expected: "Venda aprovada.",
    verify: "Verificar mensagem ao operador, recibo quando aplicavel e confirmacao/desfazimento correto para a automacao comercial.",
    sale: {
      amount: 1005.5,
      method: "credit",
      acquirer: "DEMO",
    },
  },
  {
    number: 32,
    name: "Transação pendente #2",
    mandatory: true,
    kind: "pending",
    description: "Após enviar a confirmação, o autorizador de demonstração alterará a situação para pendente. Realizar uma nova venda no valor R$1005,51.",
    procedure: "Após enviar a confirmação, o autorizador de demonstração alterará a situação para pendente. Realizar uma nova venda no valor R$1005,51.",
    expected: "A transação será negada e irá retornar os dados da transação pendente.",
    verify: "Verificar que a transacao nao seja considerada realizada pela automacao e que a mensagem/pendencia seja tratada conforme esperado.",
    sale: {
      amount: 1005.51,
      method: "credit",
      acquirer: "DEMO",
    },
  },
  {
    number: 33,
    name: "Transação pendente não encontrada #1",
    mandatory: true,
    kind: "pending",
    description: "Realizar uma venda de R$1005,60 no autorizador DEMO.",
    procedure: "Realizar uma venda de R$1005,60 no autorizador DEMO.",
    expected: "Venda aprovada.",
    verify: "Verificar mensagem ao operador, recibo quando aplicavel e confirmacao/desfazimento correto para a automacao comercial.",
    sale: {
      amount: 1005.6,
      method: "credit",
      acquirer: "DEMO",
    },
  },
  {
    number: 34,
    name: "Transação pendente não encontrada #2",
    mandatory: true,
    kind: "pending",
    description: "Após enviar a confirmação, o autorizador de demonstração irá criar uma nova transação com alguns dados que a automação não conhece. Realizar uma nova venda no valor R$1005,61.",
    procedure: "Após enviar a confirmação, o autorizador de demonstração irá criar uma nova transação com alguns dados que a automação não conhece. Realizar uma nova venda no valor R$1005,61.",
    expected: "A transação será negada e irá retornar os dados da transação pendente.",
    verify: "Verificar que a transacao nao seja considerada realizada pela automacao e que a mensagem/pendencia seja tratada conforme esperado.",
    sale: {
      amount: 1005.61,
      method: "credit",
      acquirer: "DEMO",
    },
  },
  {
    number: 35,
    name: "Confirmação #1",
    mandatory: true,
    kind: "pending",
    description: "Realizar uma venda de R$1012,00 no autorizador DEMO e realizar uma confirmação manual dessa venda.",
    procedure: "Realizar uma venda de R$1012,00 no autorizador DEMO e realizar uma confirmação manual dessa venda.",
    expected: "Venda aprovada e confirmada. Teste válido para as integrações do tipo: ● Biblioteca Windows; ● TEF Integrado Android.",
    verify: "Verificar mensagem ao operador, recibo quando aplicavel e confirmacao/desfazimento correto para a automacao comercial.",
    sale: {
      amount: 1012,
      method: "credit",
      acquirer: "DEMO",
    },
  },
  {
    number: 36,
    name: "Confirmação #2 (Opcional)",
    mandatory: false,
    kind: "pending",
    description: "Realizar uma venda de R$10,00 no autorizador REDE e realizar uma confirmação manual dessa venda.",
    procedure: "Realizar uma venda de R$10,00 no autorizador REDE e realizar uma confirmação manual dessa venda.",
    expected: "Venda aprovada e confirmada. Teste válido para as integrações do tipo: ● Biblioteca Windows; ● TEF Integrado Android.",
    verify: "Verificar mensagem ao operador, recibo quando aplicavel e confirmacao/desfazimento correto para a automacao comercial.",
    sale: {
      amount: 10,
      method: "credit",
      acquirer: "REDE",
    },
  },
  {
    number: 37,
    name: "Desfazimento manual #1",
    mandatory: true,
    kind: "pending",
    description: "Realizar uma venda de R$1011,00 no autorizador DEMO e realizar um desfazimento manual dessa transação.",
    procedure: "Realizar uma venda de R$1011,00 no autorizador DEMO e realizar um desfazimento manual dessa transação.",
    expected: "Transação será considerada desfeita. Observações ● Este teste se aplica a automações que tenham a opção de desfazer uma transação manualmente. Teste válido para as integrações do tipo: ● Biblioteca Windows; ● TEF Integrado Android.",
    verify: "Verificar mensagem ao operador, recibo quando aplicavel e confirmacao/desfazimento correto para a automacao comercial.",
    sale: {
      amount: 1011,
      method: "credit",
      acquirer: "DEMO",
    },
  },
  {
    number: 38,
    name: "Desfazimento manual #2 (Opcional)",
    mandatory: false,
    kind: "pending",
    description: "Realizar uma venda de R$333,00 no autorizador REDE e realizar um desfazimento manual dessa transação.",
    procedure: "Realizar uma venda de R$333,00 no autorizador REDE e realizar um desfazimento manual dessa transação.",
    expected: "Transação será considerada desfeita. Observações ● Este teste se aplica a automações que tenham a opção de desfazer uma transação manualmente. Teste válido para as integrações do tipo: ● Biblioteca Windows; ● TEF Integrado Android.",
    verify: "Verificar mensagem ao operador, recibo quando aplicavel e confirmacao/desfazimento correto para a automacao comercial.",
    sale: {
      amount: 333,
      method: "credit",
      acquirer: "REDE",
    },
  },
  {
    number: 39,
    name: "Desfazimento por falha na liberação da mercadoria #1",
    mandatory: true,
    kind: "pending",
    description: "Verificar se não possui a mercadoria no estoque ou alguma outra forma parecida. Realizar uma venda no valor R$1013,00.",
    procedure: "Verificar se não possui a mercadoria no estoque ou alguma outra forma parecida. Realizar uma venda no valor R$1013,00.",
    expected: "Venda aprovada. Observações ● Teste aplica-se somente para automação de autoatendimento; ● O teste será continuado no passo seguinte, PASSO 40. Teste válido para as integrações do tipo: ● Biblioteca Windows; ● TEF Integrado Android.",
    verify: "Verificar mensagem ao operador, recibo quando aplicavel e confirmacao/desfazimento correto para a automacao comercial.",
    sale: {
      amount: 1013,
      method: "credit",
      acquirer: "DEMO",
    },
  },
  {
    number: 40,
    name: "Desfazimento por falha na liberação da mercadoria #2",
    mandatory: true,
    kind: "pending",
    description: "A automação deve enviar o desfazimento por falha na liberação da mercadoria.",
    procedure: "A automação deve enviar o desfazimento por falha na liberação da mercadoria.",
    expected: "Transação será considerada desfeita. Observações ● Teste aplica-se somente para automação de autoatendimento; ● Para a automação, a transação deverá ser considerada não realizada. Teste válido para as integrações do tipo: ● Biblioteca Windows; ● TEF Integrado Android.",
    verify: "Verificar que a transacao nao seja considerada realizada pela automacao e que a mensagem/pendencia seja tratada conforme esperado.",
  },
  {
    number: 41,
    name: "Cancelamento aprovado solicitando “Referência Local” #1",
    mandatory: true,
    kind: "sale-cancel",
    description: "Realizar uma venda de R$1017,00 no autorizador DEMO.",
    procedure: "Realizar uma venda de R$1017,00 no autorizador DEMO.",
    expected: "Venda aprovada.",
    verify: "Verificar mensagem ao operador, recibo quando aplicavel e confirmacao/desfazimento correto para a automacao comercial.",
    sale: {
      amount: 1017,
      method: "credit",
      acquirer: "DEMO",
    },
  },
  {
    number: 42,
    name: "Cancelamento aprovado solicitando “Referência Local” #2",
    mandatory: true,
    kind: "cancel-prev",
    description: "Realizar o cancelamento do passo anterior.",
    procedure: "Realizar o cancelamento do passo anterior.",
    expected: "Cancelamento aprovado.",
    verify: "Verificar mensagem ao operador, recibo quando aplicavel e confirmacao/desfazimento correto para a automacao comercial.",
    cancelsStep: 41,
  },
  {
    number: 43,
    name: "Cancelamento aprovado solicitando “Referência Externa” #1",
    mandatory: true,
    kind: "sale-cancel",
    description: "Realizar uma venda de R$1018,00 no autorizador REDE.",
    procedure: "Realizar uma venda de R$1018,00 no autorizador REDE.",
    expected: "Venda aprovada.",
    verify: "Verificar mensagem ao operador, recibo quando aplicavel e confirmacao/desfazimento correto para a automacao comercial.",
    sale: {
      amount: 1018,
      method: "credit",
      acquirer: "REDE",
    },
  },
  {
    number: 44,
    name: "Cancelamento aprovado solicitando “Referência Externa” #2",
    mandatory: true,
    kind: "cancel-prev",
    description: "Realizar o cancelamento do passo anterior.",
    procedure: "Realizar o cancelamento do passo anterior.",
    expected: "Cancelamento aprovado.",
    verify: "Verificar mensagem ao operador, recibo quando aplicavel e confirmacao/desfazimento correto para a automacao comercial.",
    cancelsStep: 43,
  },
  {
    number: 45,
    name: "Venda contactless aprovada",
    mandatory: true,
    kind: "sale",
    description: "Realizar uma venda de R$1020,00 no autorizador DEMO. Quando solicitado, aproximar um cartão sem contato.",
    procedure: "Realizar uma venda de R$1020,00 no autorizador DEMO. Quando solicitado, aproximar um cartão sem contato.",
    expected: "Venda aprovada e confirmada, recibo impresso.",
    verify: "Verificar mensagem ao operador, recibo quando aplicavel e confirmacao/desfazimento correto para a automacao comercial.",
    sale: {
      amount: 1020,
      method: "credit",
      acquirer: "DEMO",
    },
  },
  {
    number: 46,
    name: "Venda contactless aprovada sem senha",
    mandatory: true,
    kind: "sale",
    description: "Realizar uma venda de R$999,00 no autorizador DEMO. Quando solicitado, aproximar um cartão sem contato.",
    procedure: "Realizar uma venda de R$999,00 no autorizador DEMO. Quando solicitado, aproximar um cartão sem contato.",
    expected: "Venda aprovada e confirmada, recibo impresso.",
    verify: "Verificar mensagem ao operador, recibo quando aplicavel e confirmacao/desfazimento correto para a automacao comercial.",
    sale: {
      amount: 999,
      method: "credit",
      acquirer: "DEMO",
    },
  },
  {
    number: 47,
    name: "Consulta de terminais",
    mandatory: false,
    kind: "controlpay-na",
    description: "Realize uma consulta dos terminais disponíveis, utilizar a API para consulta.",
    procedure: "Realize uma consulta dos terminais disponíveis, utilizar a API para consulta.",
    expected: "Status 200 OK. Teste válido para as integrações do tipo: ● Pagamento via Web Service (ControlPay).",
    verify: "Verificar mensagem ao operador, recibo quando aplicavel e confirmacao/desfazimento correto para a automacao comercial.",
  },
  {
    number: 48,
    name: "Consultar status de uma transação #1",
    mandatory: false,
    kind: "controlpay-na",
    description: "Realize uma consulta da transação realizada no PASSO 2.",
    procedure: "Realize uma consulta da transação realizada no PASSO 2.",
    expected: "Status 200 OK. Teste válido para as integrações do tipo: ● Pagamento via Web Service (ControlPay).",
    verify: "Verificar mensagem ao operador, recibo quando aplicavel e confirmacao/desfazimento correto para a automacao comercial.",
  },
  {
    number: 49,
    name: "Consultar status de uma transação #2",
    mandatory: false,
    kind: "controlpay-na",
    description: "Realize uma consulta da transação realizada no PASSO 6.",
    procedure: "Realize uma consulta da transação realizada no PASSO 6.",
    expected: "Status 200 OK. Teste válido para as integrações do tipo: ● Pagamento via Web Service (ControlPay).",
    verify: "Verificar mensagem ao operador, recibo quando aplicavel e confirmacao/desfazimento correto para a automacao comercial.",
  },
  {
    number: 50,
    name: "Callback de venda",
    mandatory: false,
    kind: "controlpay-na",
    description: "Realize o callback da venda realizada no PASSO 6.",
    procedure: "Realize o callback da venda realizada no PASSO 6.",
    expected: "Status 200 OK. Teste válido para as integrações do tipo: ● Pagamento via Web Service (ControlPay).",
    verify: "Verificar mensagem ao operador, recibo quando aplicavel e confirmacao/desfazimento correto para a automacao comercial.",
  },
  {
    number: 51,
    name: "Queda de energia após a aprovação",
    mandatory: true,
    kind: "power-cut",
    description: "Realizar uma venda. Ao receber o resultado da transação, antes de enviar a confirmação, desligar o checkout de maneira abrupta. Reiniciar os sistemas envolvidos e desfazer a transação que nesse momento estará pendente.",
    procedure: "Realizar uma venda. Ao receber o resultado da transação, antes de enviar a confirmação, desligar o checkout de maneira abrupta. Reiniciar os sistemas envolvidos e desfazer a transação que nesse momento estará pendente.",
    expected: "Transação não realizada para a automação comercial. Teste válido para as integrações do tipo: ● Troca de arquivos txt; ● Biblioteca Windows.",
    verify: "Verificar que a transacao nao seja considerada realizada pela automacao e que a mensagem/pendencia seja tratada conforme esperado.",
  },
  {
    number: 52,
    name: "Operação cancelada durante venda PIX",
    mandatory: true,
    kind: "manual",
    description: "Realizar uma venda e na tela de exibição do QRCode, pressionar a tecla ‘Esc’ em uma solução Windows ou ‘Cancelar’ em uma solução Android.",
    procedure: "Realizar uma venda e na tela de exibição do QRCode, pressionar a tecla ‘Esc’ em uma solução Windows ou ‘Cancelar’ em uma solução Android.",
    expected: "Venda negada.",
    verify: "Verificar que a transacao nao seja considerada realizada pela automacao e que a mensagem/pendencia seja tratada conforme esperado.",
  },
  {
    number: 53,
    name: "Venda por QRCode para PIX e Carteiras Digitais",
    mandatory: true,
    kind: "sale-cancel",
    description: "Realizar uma venda no valor de R$500,00, no autorizador “PIX C6 BANK”, aguardando aprovação automática.",
    procedure: "Realizar uma venda no valor de R$500,00, no autorizador “PIX C6 BANK”, aguardando aprovação automática.",
    expected: "Venda aprovada e confirmada, recibo impresso.",
    verify: "Verificar mensagem ao operador, recibo quando aplicavel e confirmacao/desfazimento correto para a automacao comercial.",
    sale: {
      amount: 500,
      method: "pix",
      acquirer: "PIX C6 BANK",
    },
  },
  {
    number: 54,
    name: "Cancelamento PIX",
    mandatory: true,
    kind: "cancel-prev",
    description: "Realizar o cancelamento da venda realizada no PASSO 53.",
    procedure: "Realizar o cancelamento da venda realizada no PASSO 53.",
    expected: "Cancelamento negado.",
    verify: "Verificar que a transacao nao seja considerada realizada pela automacao e que a mensagem/pendencia seja tratada conforme esperado.",
    cancelsStep: 53,
  },
];
