ALTER TABLE public.employees
  ADD COLUMN IF NOT EXISTS ctps_number text,
  ADD COLUMN IF NOT EXISTS ctps_series text,
  ADD COLUMN IF NOT EXISTS ctps_uf text,
  ADD COLUMN IF NOT EXISTS ctps_issue_date date,
  ADD COLUMN IF NOT EXISTS rg_issuer text,
  ADD COLUMN IF NOT EXISTS rg_issue_date date,
  ADD COLUMN IF NOT EXISTS rg_uf text,
  ADD COLUMN IF NOT EXISTS esocial_category text,
  ADD COLUMN IF NOT EXISTS work_regime text,
  ADD COLUMN IF NOT EXISTS journey_type text,
  ADD COLUMN IF NOT EXISTS weekly_hours numeric,
  ADD COLUMN IF NOT EXISTS monthly_hours numeric,
  ADD COLUMN IF NOT EXISTS salary_type text,
  ADD COLUMN IF NOT EXISTS hazard_pay_type text,
  ADD COLUMN IF NOT EXISTS hazard_pay_percent numeric,
  ADD COLUMN IF NOT EXISTS first_job boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS union_member boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS is_apprentice boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS disability_type text,
  ADD COLUMN IF NOT EXISTS cnh_number text,
  ADD COLUMN IF NOT EXISTS cnh_category text,
  ADD COLUMN IF NOT EXISTS cnh_expiration date,
  ADD COLUMN IF NOT EXISTS passport_number text,
  ADD COLUMN IF NOT EXISTS foreigner_rnm text,
  ADD COLUMN IF NOT EXISTS foreigner_visa_type text,
  ADD COLUMN IF NOT EXISTS foreigner_arrival_date date;